package com.routex.model;

import java.sql.Timestamp;

/** A notification delivered to a user, generated by the Observer pattern in Live Trip Management. */
public class Notification {

    private long id;
    private long userId;
    private String message;
    private String type;
    private boolean read;
    private Timestamp createdAt;

    public Notification(long id, long userId, String message, String type, boolean read, Timestamp createdAt) {
        this.id = id;
        this.userId = userId;
        this.message = message;
        this.type = type;
        this.read = read;
        this.createdAt = createdAt;
    }

    public long getId() { return id; }
    public long getUserId() { return userId; }
    public String getMessage() { return message; }
    public String getType() { return type; }
    public boolean isRead() { return read; }
    public Timestamp getCreatedAt() { return createdAt; }
}
